export const tokens = {
  colorAction: '--color-action',
  colorActionText: '--color-action-text',
  colorSurface: '--color-surface',
  colorText: '--color-text',
  colorTextSecondary: '--color-text-secondary',
  colorTextMuted: '--color-text-muted',
  colorBorder: '--color-border',
  colorDisabledBg: '--color-disabled-bg',
  colorDisabledText: '--color-disabled-text',
  chatBubbleThemBg: '--chat-bubble-them-bg',
  chatBubbleMineBg: '--chat-bubble-mine-bg',
  chatBubbleMineText: '--chat-bubble-mine-text',
  chatInputBg: '--chat-input-bg',
  chatInputBorder: '--chat-input-border',
  mapPinYou: '--map-pin-you',
  mapPinPartner: '--map-pin-partner',
  mapPinDestination: '--map-pin-destination',
} as const;
